blank_issues_enabled: true
contact_links:
  - name: Hugo / Structure issue
    url: https://github.com/nkdAgility/HugoGuides/issues
    about: If you find a problem with the structure of the site, please report it here. This module supports a number of sites.
